<h1 style="color:green" align='center'>Numpy tutorial: iterate numpy array using nditer</h1>

In [50]:
import numpy as np

In [51]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

<h3 style="color:purple">Using normal for loop iteration</h3>

In [52]:
for row in  a:   #iterate through only rows and prints rows
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [53]:
for row in a:
    for cell in row:         #iterate through each cell in those rows and prints each cell
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


<h3 style="color:purple">Iterating using For loop with flatten</h3>

In [54]:
for cell in a.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


<h1 style="color:blue" align="center">nditer</h1>

numpy.nditer is an iterator object in NumPy that provides a flexible way to iterate over elements of multi-dimensional arrays.

The nditer object allows you to iterate over arrays with different strides, shapes, and data types while providing a unified interface.



<h3 style="color:Blue">order parameter:</h3>

C-order traversal - row major

F-order traversal - Column major

<h3 style="color:purple">C style ordering</h3>

In [55]:
for x in np.nditer(a, order='C'):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


<h2 style="color:purple">Fortan style ordering</h2>

In [56]:
for x in np.nditer(a, order='F'):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


<h3 style="color:Blue">External_loop flag parameter</h3>

The external loop flag (external_loop) is a parameter in the numpy.nditer function that specifies whether the iterator should treat the last loop as an external loop. The external loop refers to the outermost loop in a nested loop structure when iterating over multiple arrays.

In [57]:
for x in np.nditer(a,order='C',flags=['external_loop']):
    print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


<h3 style="color:Blue">readwrite flag parameter</h3>

to modify the values of the array during iteration

In [58]:
for x in np.nditer(a, op_flags=['readwrite']):
    x[...] = x * x

In [59]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

<h2 style="color:purple">Iterate two broadcastable arrays concurrently</h2>

while iterating 2 arrays, the sizes are should equal or it has 1 same row / column

In [60]:
b = np.arange(3, 15, 4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [61]:
for x, y in np.nditer([a,b]):
    print (x,y)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11
